complete -c ebook-homebrew-rust-client -n "__fish_use_subcommand" -s v -l version -d 'CLI version'
complete -c ebook-homebrew-rust-client -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c ebook-homebrew-rust-client -n "__fish_use_subcommand" -f -a "upload" -d 'upload image files'
complete -c ebook-homebrew-rust-client -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c ebook-homebrew-rust-client -n "__fish_seen_subcommand_from upload" -l host -d 'ebook-homebrew host URL'
complete -c ebook-homebrew-rust-client -n "__fish_seen_subcommand_from upload" -l port -d 'ebook-homebrew port'
complete -c ebook-homebrew-rust-client -n "__fish_seen_subcommand_from upload" -s h -l help -d 'Prints help information'
complete -c ebook-homebrew-rust-client -n "__fish_seen_subcommand_from upload" -s V -l version -d 'Prints version information'
complete -c ebook-homebrew-rust-client -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c ebook-homebrew-rust-client -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
