version: 2.1

executors:
  default:
    docker:
      - image: 'rust:1.34-stretch'
    environment:
      MAKE_LIBSASS_JOBS: '4'
      BUILD_JOBS: '4'

jobs:
  lint:
    executor: 'default'
    steps:
      - 'checkout'
      - run: 'rustup component add rustfmt'
      - run: 'cargo fmt -- --check'
  build:
    executor: 'default'
    parameters:
      release:
        type: 'boolean'
        default: false
    steps:
      - 'checkout'
      - restore_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}<<# parameters.release >>-release<</ parameters.release>>'
      - run: 'cargo build --jobs ${BUILD_JOBS} <<# parameters.release >>--release --locked<</ parameters.release>>'
      - save_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}<<# parameters.release >>-release<</ parameters.release>>'
          paths:
            - '/usr/local/cargo/registry'
            - 'target/'
  test:
    executor: 'default'
    parameters:
      release:
        type: 'boolean'
        default: false
    steps:
      - 'checkout'
      - restore_cache:
          key: 'v1-cargo-lock-{{ checksum "Cargo.lock"}}<<# parameters.release >>-release<</ parameters.release>>'
      - run: 'cargo test <<# parameters.release >>--release --locked<</ parameters.release>>'

workflows:
  version: 2
  run_test:
    jobs:
      - 'lint'
      - 'build'
      - test:
          requires:
            - 'lint'
            - 'build'
  release:
    jobs:
      - lint:
          filters:
            branches:
              only: 'master'
      - build:
          release: true
          filters:
            branches:
              only: 'master'
      - test:
          release: true
          requires:
            - 'lint'
            - 'build'
          filters:
            branches:
              only: 'master'
